# Generated by Django 4.1.7 on 2023-03-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=50)),
                ('farm_token', models.CharField(max_length=50)),
                ('price_token', models.CharField(max_length=50)),
            ],
        ),
    ]
