# Generated by Django 4.1.7 on 2023-03-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferms',
            options={'ordering': ['id']},
        ),
    ]
